[supabase]
url = "https://nglfinstlkylrrtqgymg.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nbGZpbnN0bGt5bHJydHFneW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU0NTg1MjEsImV4cCI6MjA4MTAzNDUyMX0.XresMI-dU3cOpqYBtRS_Exw76slqXcN6qOtc42QQFHY"






